### ISSUE TITLE
Pop and clear handlers

### ISSUE THREAD

**Issue by rhofour** [qtux/myo-raw#7]
I'd like to add support to clear all of a certain type of handler (ex: clear_imu_handlers) and to remove the most recent one (ex: pop_imu_handler).

While I do this I could rename the add_X_handler functions to push_X_handler to better match the new pop_X_handler functions I'm adding. Do you think this is worth doing or should I preserve backwards compatibility and only add the new ones?

**Comment by qtux** [comment]
Your push/pop solution sounds good to me, feel free to rename the add_X_handler functions :).
